version: '3.7'

services:
  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15673:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  fossbilling:
    build: ./fossbilling
    container_name: fossbilling
    ports:
      - "8090:80"
    depends_on:
      - foss_db
    environment:
      DB_HOST: foss_db
      DB_USER: fossuser
      DB_PASSWORD: fosspassword
      DB_NAME: fossbilling
    volumes:
      - fossbilling_data:/var/www/html
      - fossbilling_config:/var/www/html/config

  foss_db:
    image: mysql:5.7
    container_name: foss_db
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossuser
      MYSQL_PASSWORD: fosspassword
      MYSQL_ROOT_PASSWORD: fossrootpassword
    volumes:
      - foss_db_data:/var/lib/mysql

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
      - fossbilling
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  consumerfoss:
    build: ./consumerfoss
    container_name: consumerfoss
    depends_on:
      - rabbitmq
      - wordpress
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

volumes:
  wordpress_data:
  db_data:
  fossbilling_data:
  fossbilling_config:
  foss_db_data:
