name: Build and Deploy

on:
  push:
    branches:
      - Dev  

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Utilisation du runner auto-hébergé

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build consumer image
        run: |
          cd consumer
          docker build -t consumer:latest .

      - name: Build consumerfoss image
        run: |
          cd consumerfoss
          docker build -t consumerfoss:latest .

      - name: Build fossbilling image
        run: |
          cd fossbilling
          docker build -t fossbilling:latest .

      - name: Build wordpress image
        run: |
          cd wordpress
          docker build -t wordpress:latest .

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER }}  
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          scp -v /home/hamza/integration/docker-compose.yml hamza@$SERVER_IP:/home/hamza/integration
          ssh hamza@$SERVER_IP "cd /home/hamza/integration && docker-compose down && docker-compose up -d"
